/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.skyreco.view;

import static com.skyreco.view.home.CheckModelRepeat;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author aayus
 */
public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
       //adding image in the frame and icon
        Image icon= new ImageIcon(this.getClass().getResource("LOGO (2) (1) (1) (1).png")).getImage();
        this. setIconImage(icon);
    }
    
    //for closing the add frame once the values are added into the table
    public void close(){
        WindowEvent closeWindows = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindows);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        HomeB2 = new javax.swing.JButton();
        AddB2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ModelNumberTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CompanyTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CameraTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RangeSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CostTxt = new javax.swing.JTextField();
        PurposeComboBox = new javax.swing.JComboBox<>();

        jTextField4.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        HomeB2.setBackground(new java.awt.Color(102, 153, 0));
        HomeB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skyreco/view/homeIcon.png"))); // NOI18N
        HomeB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeB2ActionPerformed(evt);
            }
        });

        AddB2.setBackground(new java.awt.Color(102, 0, 0));
        AddB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skyreco/view/add.png"))); // NOI18N
        AddB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddB2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Model Number");

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 26)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skyreco/view/LOGO (2) (1) (1) (1).png"))); // NOI18N

        ModelNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelNumberTxtActionPerformed(evt);
            }
        });
        ModelNumberTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ModelNumberTxtKeyPressed(evt);
            }
        });

        jLabel2.setText("Name");

        NameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTxtActionPerformed(evt);
            }
        });
        NameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameTxtKeyPressed(evt);
            }
        });

        jLabel4.setText("Company");

        CompanyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CompanyTxtKeyPressed(evt);
            }
        });

        jLabel5.setText("Camera");

        CameraTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CameraTxtKeyPressed(evt);
            }
        });

        jLabel6.setText("Range");

        RangeSpinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RangeSpinnerKeyPressed(evt);
            }
        });

        jLabel7.setText("Purpose");

        jLabel8.setText("Cost (IN USD)");

        CostTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CostTxtKeyTyped(evt);
            }
        });

        PurposeComboBox.setBackground(new java.awt.Color(250, 237, 237));
        PurposeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Videography", "Photography", "Surveillance" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CostTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                            .addComponent(CameraTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CompanyTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                            .addComponent(NameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModelNumberTxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RangeSpinner)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addGap(354, 354, 354))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PurposeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(31, 31, 31))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(HomeB2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddB2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(ModelNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CompanyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CameraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RangeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PurposeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddB2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeB2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeB2ActionPerformed
        //for returning to the home frame
        close();
    }//GEN-LAST:event_HomeB2ActionPerformed

    private void AddB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddB2ActionPerformed
        
        
        //checking if the textfield is empty
        if(ModelNumberTxt.getText().equals("")||NameTxt.getText().equals("")||CompanyTxt.getText().equals("")||
                CostTxt.getText().equals("")||CameraTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please!! Enter all the value!");
        }
        else{
            //checking if the model number repeats by calling the function of the home class
            if(CheckModelRepeat(ModelNumberTxt.getText())){
                JOptionPane.showMessageDialog(this,"Model Number cannot be same! Please try another value!");
            }
            else{
                home.AddRowToJTable(new Object[]{
                home.snsetter(),
                ModelNumberTxt.getText(),
                NameTxt.getText(),
                CompanyTxt.getText(),
                CameraTxt.getText(),
                RangeSpinner.getValue(),
                CostTxt.getText(),
                PurposeComboBox.getSelectedItem()
                });
                JOptionPane.showMessageDialog(this,"Sucessfully added!");
                close();
            }
        }
        
    }//GEN-LAST:event_AddB2ActionPerformed

    private void ModelNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelNumberTxtActionPerformed

    private void NameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtActionPerformed

    private void CostTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CostTxtKeyTyped
        //only letting the numbers to be written in this
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            evt.consume();
            JOptionPane.showMessageDialog(this,"Please enter only numbers");
        }
    }//GEN-LAST:event_CostTxtKeyTyped

    private void RangeSpinnerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RangeSpinnerKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_RangeSpinnerKeyPressed

    private void CompanyTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CompanyTxtKeyPressed
        //only accept letters, space bar and delete backspace
        char c= evt.getKeyChar();
        
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            CompanyTxt.setEditable(true);
        }
        else{
            CompanyTxt.setEditable(false);
            JOptionPane.showMessageDialog(this,"Special character and numbers are not accepted! Please Enter proper Company!");
        }
    }//GEN-LAST:event_CompanyTxtKeyPressed

    private void NameTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameTxtKeyPressed
        //only accept letters, space bar,number and delete backspace
        char c= evt.getKeyChar();
        
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||Character.isDigit(c)||c=='-'){
            NameTxt.setEditable(true);
        }
        else{
            NameTxt.setEditable(false);
            JOptionPane.showMessageDialog(this,"Special character are not accepted! Please Enter proper name!");
        }
    }//GEN-LAST:event_NameTxtKeyPressed

    private void ModelNumberTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModelNumberTxtKeyPressed
        //only accept letters, space bar,number and delete backspace
        char c= evt.getKeyChar();
        
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||Character.isDigit(c)||c=='-'){
            ModelNumberTxt.setEditable(true);
        }
        else{
            ModelNumberTxt.setEditable(false);
            JOptionPane.showMessageDialog(this,"Special character are not accepted! Please Enter proper Model Number!");
        }
    }//GEN-LAST:event_ModelNumberTxtKeyPressed

    private void CameraTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CameraTxtKeyPressed
        //only accept letters, space bar and delete backspace
        char c= evt.getKeyChar();
        
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||c=='.'||c=='-'||Character.isDigit(c)){
            CameraTxt.setEditable(true);
        }
        else{
            CameraTxt.setEditable(false);
            JOptionPane.showMessageDialog(this,"Special character are not accepted! Please Enter proper Camera!");
        }
    }//GEN-LAST:event_CameraTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Add().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddB2;
    private javax.swing.JTextField CameraTxt;
    private javax.swing.JTextField CompanyTxt;
    private javax.swing.JTextField CostTxt;
    private javax.swing.JButton HomeB2;
    private javax.swing.JTextField ModelNumberTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JComboBox<String> PurposeComboBox;
    private javax.swing.JSpinner RangeSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
