/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.skyreco.view;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author aayus
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
        //for getting the image for logo and icon
        Image icon= new ImageIcon(this.getClass().getResource("LOGO (2) (1) (1) (1).png")).getImage();
        this. setIconImage(icon);
    }
    
    public void close(){
        // for closing the update frame
        WindowEvent closeWindows = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindows);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ModelNumlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ModelNumberTxt = new javax.swing.JTextField();
        Namelabel = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        Companylabel = new javax.swing.JLabel();
        CompanyTxt = new javax.swing.JTextField();
        Cameralabel = new javax.swing.JLabel();
        CameraTxt = new javax.swing.JTextField();
        Rangelabel = new javax.swing.JLabel();
        Purposelabel = new javax.swing.JLabel();
        Costlabel = new javax.swing.JLabel();
        CostTxt = new javax.swing.JTextField();
        PurposeComboBox = new javax.swing.JComboBox<>();
        UpdateB = new javax.swing.JButton();
        SNtxt = new javax.swing.JTextField();
        SNlabel = new javax.swing.JLabel();
        HomeB = new javax.swing.JButton();
        Rangetxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ModelNumlabel.setText("Model Number");

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 26)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skyreco/view/LOGO (2) (1) (1) (1).png"))); // NOI18N

        ModelNumberTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModelNumberTxtMouseClicked(evt);
            }
        });
        ModelNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelNumberTxtActionPerformed(evt);
            }
        });
        ModelNumberTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ModelNumberTxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ModelNumberTxtKeyTyped(evt);
            }
        });

        Namelabel.setText("Name");

        NameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameTxtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NameTxtMousePressed(evt);
            }
        });
        NameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTxtActionPerformed(evt);
            }
        });
        NameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameTxtKeyPressed(evt);
            }
        });

        Companylabel.setText("Company");

        CompanyTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompanyTxtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CompanyTxtMousePressed(evt);
            }
        });
        CompanyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CompanyTxtKeyPressed(evt);
            }
        });

        Cameralabel.setText("Camera");

        CameraTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CameraTxtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CameraTxtMousePressed(evt);
            }
        });
        CameraTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CameraTxtKeyPressed(evt);
            }
        });

        Rangelabel.setText("Range");

        Purposelabel.setText("Purpose");

        Costlabel.setText("Cost (IN USD)");

        CostTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CostTxtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CostTxtMousePressed(evt);
            }
        });
        CostTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CostTxtKeyTyped(evt);
            }
        });

        PurposeComboBox.setBackground(new java.awt.Color(250, 237, 237));
        PurposeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Videography", "Photography", "Surveillance" }));

        UpdateB.setBackground(new java.awt.Color(0, 153, 102));
        UpdateB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skyreco/view/update.png"))); // NOI18N
        UpdateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBActionPerformed(evt);
            }
        });

        SNtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNtxtActionPerformed(evt);
            }
        });
        SNtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SNtxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SNtxtKeyTyped(evt);
            }
        });

        SNlabel.setText("S.N.");

        HomeB.setBackground(new java.awt.Color(102, 153, 0));
        HomeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skyreco/view/homeIcon.png"))); // NOI18N
        HomeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBActionPerformed(evt);
            }
        });

        Rangetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RangetxtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RangetxtMousePressed(evt);
            }
        });
        Rangetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RangetxtKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Rangelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cameralabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Companylabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Namelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ModelNumlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Costlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rangetxt))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Purposelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(354, 354, 354))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PurposeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(31, 31, 31))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SNlabel)
                                    .addComponent(SNtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(186, 186, 186)
                                .addComponent(jLabel3))
                            .addComponent(ModelNumberTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                            .addComponent(NameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CompanyTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CameraTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CostTxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(23, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(HomeB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SNlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SNtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ModelNumlabel)
                .addGap(12, 12, 12)
                .addComponent(ModelNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Namelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Companylabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CompanyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cameralabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CameraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rangelabel)
                    .addComponent(Purposelabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PurposeComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(Rangetxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Costlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(HomeB, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UpdateB, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModelNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelNumberTxtActionPerformed

    private void NameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtActionPerformed

    private void CostTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CostTxtKeyTyped
        //only accept number 
        char c= evt.getKeyChar();
        
        if(Character.isDigit(c)){
            CostTxt.setEditable(true);
        }
        else{
            CostTxt.setEditable(false);
            JOptionPane.showMessageDialog(this,"Please enter only numbers");
        }
    }//GEN-LAST:event_CostTxtKeyTyped

    private void UpdateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBActionPerformed
        //checking if the textfield is empty
        if(ModelNumberTxt.getText().equals("")||NameTxt.getText().equals("")||CompanyTxt.getText().equals("")||
                CostTxt.getText().equals("")||CameraTxt.getText().equals("")||SNtxt.getText().equals("")||Rangetxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please!! Enter all the value!");
        }
        else{
            home.UpdateRow(new Object[]{
            SNtxt.getText(),
            ModelNumberTxt.getText(),
            NameTxt.getText(),
            CompanyTxt.getText(),
            CameraTxt.getText(),
            Rangetxt.getText(),
            CostTxt.getText(),
            PurposeComboBox.getSelectedItem()
            });
            JOptionPane.showMessageDialog(this,"Values are Updated");
            close();
            
        }
    }//GEN-LAST:event_UpdateBActionPerformed

    private void SNtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNtxtActionPerformed

    private void HomeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBActionPerformed
        close();
    }//GEN-LAST:event_HomeBActionPerformed

    private void SNtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SNtxtKeyTyped
        SNtxt.setEditable(false);
    }//GEN-LAST:event_SNtxtKeyTyped

    private void ModelNumberTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModelNumberTxtMouseClicked
    }//GEN-LAST:event_ModelNumberTxtMouseClicked

    private void NameTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameTxtMouseClicked
        
    }//GEN-LAST:event_NameTxtMouseClicked

    private void CompanyTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompanyTxtMouseClicked
        
    }//GEN-LAST:event_CompanyTxtMouseClicked

    private void CameraTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CameraTxtMouseClicked
        
    }//GEN-LAST:event_CameraTxtMouseClicked

    private void RangetxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RangetxtMouseClicked
        
    }//GEN-LAST:event_RangetxtMouseClicked

    private void CostTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CostTxtMouseClicked
        
    }//GEN-LAST:event_CostTxtMouseClicked

    private void ModelNumberTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModelNumberTxtKeyTyped
    }//GEN-LAST:event_ModelNumberTxtKeyTyped

    private void SNtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SNtxtKeyPressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"This cannot be changed!");
        SNtxt.setEditable(false);
    }//GEN-LAST:event_SNtxtKeyPressed

    private void ModelNumberTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModelNumberTxtKeyPressed
        //only accept letters, space bar,number and delete backspace
        char c= evt.getKeyChar();
        
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||Character.isDigit(c)||c=='-'){
            ModelNumberTxt.setEditable(true);
        }
        else{
            ModelNumberTxt.setEditable(false);
            JOptionPane.showMessageDialog(this,"Special character are not accepted! Please Enter proper Model Number!");
        }
    }//GEN-LAST:event_ModelNumberTxtKeyPressed

    private void CompanyTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompanyTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyTxtMousePressed

    private void NameTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtMousePressed

    private void CameraTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CameraTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CameraTxtMousePressed

    private void RangetxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RangetxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_RangetxtMousePressed

    private void CostTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CostTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostTxtMousePressed

    private void RangetxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RangetxtKeyPressed
        //only accept numbers
        char c= evt.getKeyChar();
        
        if(Character.isDigit(c)||Character.isISOControl(c)){
            Rangetxt.setEditable(true);
        }
        else{
            Rangetxt.setEditable(false);
            JOptionPane.showMessageDialog(this,"Special character and letters are not accepted! Please Enter proper Range!");
        }
    }//GEN-LAST:event_RangetxtKeyPressed

    private void NameTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameTxtKeyPressed
        //only accept letters, space bar,number and delete backspace
        char c= evt.getKeyChar();
        
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||Character.isDigit(c)||c=='-'){
            NameTxt.setEditable(true);
        }
        else{
            NameTxt.setEditable(false);
            JOptionPane.showMessageDialog(this,"Special character are not accepted! Please Enter proper name!");
        }
    }//GEN-LAST:event_NameTxtKeyPressed

    private void CompanyTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CompanyTxtKeyPressed
        //only accept letters, space bar and delete backspace
        char c= evt.getKeyChar();
        
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            CompanyTxt.setEditable(true);
        }
        else{
            CompanyTxt.setEditable(false);
            JOptionPane.showMessageDialog(this,"Special character and numbers are not accepted! Please Enter proper Company!");
        }
    }//GEN-LAST:event_CompanyTxtKeyPressed

    private void CameraTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CameraTxtKeyPressed
        //only accept letters, space bar and delete backspace
        char c= evt.getKeyChar();
        
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)||c=='.'||c=='-'||Character.isDigit(c)){
            CameraTxt.setEditable(true);
        }
        else{
            CameraTxt.setEditable(false);
            JOptionPane.showMessageDialog(this,"Special character and numbers are not accepted! Please Enter proper Camera!");
        }    }//GEN-LAST:event_CameraTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField CameraTxt;
    private javax.swing.JLabel Cameralabel;
    public javax.swing.JTextField CompanyTxt;
    private javax.swing.JLabel Companylabel;
    public javax.swing.JTextField CostTxt;
    private javax.swing.JLabel Costlabel;
    private javax.swing.JButton HomeB;
    public javax.swing.JTextField ModelNumberTxt;
    private javax.swing.JLabel ModelNumlabel;
    public javax.swing.JTextField NameTxt;
    private javax.swing.JLabel Namelabel;
    public javax.swing.JComboBox<String> PurposeComboBox;
    private javax.swing.JLabel Purposelabel;
    private javax.swing.JLabel Rangelabel;
    public javax.swing.JTextField Rangetxt;
    private javax.swing.JLabel SNlabel;
    public javax.swing.JTextField SNtxt;
    private javax.swing.JButton UpdateB;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
